version: "2"
services:
  neo4j:
    image: "npmspy/neo4j:latest"
    ports:
     - "7474:7474"
     - "7687:7687"
    volumes:
     - $HOME/neo4j/data2:/data
     - $HOME/neo4j/logs:/logs
    environment:
      NEO4J_AUTH: 'neo4j/correct-horse-battery-staple'

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    ports:
     - "8080:15672"
     - "5671:5671"
     - "5672:5672"

  listener:
    image: "npmspy/change-listener:latest"
    depends_on:
     - "rabbitmq"
    environment:
      REPLICATION_HOST: "https://replicate.npmjs.com"
      QUEUE_HOST: "rabbitmq"
      PRIORITY_QUEUE: "priority"

  importer:
    image: "npmspy/db-importer:latest"
    depends_on:
     - "neo4j"
     - "rabbitmq"
    environment:
      REPLICATION_HOST: "https://replicate.npmjs.com"
      QUEUE_HOST: "rabbitmq"
      PRIORITY_QUEUE: "priority"
      NEO4J_HOST: "neo4j"
      NEO4J_AUTH: "bmVvNGo6Y29ycmVjdC1ob3JzZS1iYXR0ZXJ5LXN0YXBsZQ=="